



title: my Github Site

url: "http://jmstan.github.io/my-site/"

baseurl: "my-site"
permalink: pretty

gems:
-jemoji
-jekyll-sitemap

sitemap:
      file: "/sitemap.xml"
      exclude:
          - "/im.html"
      include_posts:
          - "/index.html"
      change_frequency_name: "change_frequency"
      priority_name: "priority"



prose:
  siteurl: "http://jmstan.github.io/my-site" 
  media: 'media'
  rooturl: '_posts'
  ignore: 
    - index.html
    - _includes.html
    - _layouts.html
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"